CREATE OR REPLACE FUNCTION func_minimum (VARIADIC arr NUMERIC[])
RETURNS NUMERIC AS
$BODY$
BEGIN
    RETURN (SELECT MIN(i) FROM unnest(arr) i);
END;
$BODY$
LANGUAGE plpgsql;

SELECT func_minimum(VARIADIC arr => ARRAY[10.0, -1.0, 5.0, 4.4]);